spring:
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost
    preferIpAddress: true
    instanceId: ${spring.application.name}:${instanceId:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: always
