server:
  port: 8083
spring:
  application:
    name: enrollment-service
  config:
    import: optional:configserver:http://config-server
  datasource:
    url: jdbc:postgresql://localhost:5432/enrollment-db
    username: postgres
    password: Venky@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
